# To deploy the site in production:
# - build the site locally using the command: bundle exec jekyll serve -d ./docs
# - push the files to the master branch on the remote repo
# - you're done!



# Site settings
url: 'https://alexpoint.github.io/theuniversaldb'
baseurl: ''
contact_email: contact@incspecs.com


# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md
    - docs
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# We use a custom plugin for localization (with one version of the website in various languages).
# On top of that, we use a modified version of the plugin so that the default version (English) is under the URL /en
# See https://www.klaasnotfound.com/2017/02/16/proper-multilingual-site-with-github-pages-and-jekyll/ (point 1.)
# The language setting is used in /includes/header.html for html-settings
# We support only English for now - the multi-language mechanism is in place for easier localization later
languages: ["en"]
exclude_from_localizations: ["CNAME", "assets"]
defaultLang: en
languageNames:
  en: English


# Analytics
# used in _includes/footer_scripts
google_analytics_tracking_id: UA-147974594-1